joaoseckler/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    re_path(r"^comments/", include("django_comments.urls")),
    path("laialaia/", include("laialaia.urls")),
    path("api/auth/", include("authentication.urls")),
    path("api/repetition/", include("repetition.urls")),
    path("admin/", admin.site.urls),
    re_path(r"^\>/", include("tagform.urls")),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
    re_path(r"^(?!admin)", include("pages.urls")),
]

pages/urls.py
from django.urls import path, re_path, include
from . import views
from custom_comments.views import post_comment
import os, re

app_name = 'pages'
urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(
        r'^(?P<name>.+)/(comments|discussão)/post$',
        post_comment,
        name='post'
    ),
    re_path(
        r'^(?P<name>.+)/(comments|discussão)$',
        views.comments,
        name='comments'
    ),
    re_path(r'^(?P<name>.+)/meta$', views.meta, name='meta'),
    re_path(r'^(?P<name>.+)$', views.view, name='page'),
]

pages/templates/pages/base.html
{% load static %}
{% load i18n %}

{% load rutf %}
{% load page_tags %}

{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}

<!DOCTYPE html>
<html lang={{ LANGUAGE_CODE }}>
  <head>
    <title>{{ o.title | default:'João Seckler'}}</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Crimson+Text:ital,wght@0,400;0,600;0,700;1,400;1,600;1,700&family=Inconsolata:wght@400;700&display=block" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content={{ o.keywords | default:"joão,seckler"}}>

    {% trans 'Sharing some things' as tr %}
    <meta name="description" content="{{ o.shortdescription |default:tr}}">

    {% utf_value as u %}
    {% with u|add:'.ico' as f %}
    {% with u|add:'ogp.jpg' as fogp %}
    <link rel="icon" href="{% static f %}" type="image/png">
    <meta content= "{% absolute_static request fogp %}" property="og:image">
    <meta content="1200" property="og:image:width">
    <meta content="630" property="og:image:height">
    <meta content="image/jpeg" property="og:image:type">
    {% endwith %}
    {% endwith %}

    <meta content="{{ o.shortdescription |default:tr}}" property= "og:description">
    <meta content="{{ o.title | default:'João Seckler'}}" property="og:title">
    <meta content="article" property="og:type">

    {% if request.path %}
      <meta content="{{ request.build_absolute_uri }}" property="og:url"/>
    {% endif %}
    <meta content="João Seckler" property="og:site_name">
    <meta content="João Seckler" property= "og:image:alt">
    <meta content="index,follow" name="robots">

    {% if LANGUAGE_CODE == 'pt' %}
      <link rel="canonical" href="{{ request.build_absolute_uri }}" />
    {% endif %}

    {% for lang_code, lang_name in LANGUAGES %}
      {% with lang_code|add:"_version" as att %} {# att = lang[0] + '_version'#}
      {% with o|getattrfilter:att as l %} {# l = getattr(o, att) #}
        {% if l %}
          {% if lang_code == 'pt' %}
            <link rel="canonical" href="{% absolute_url request 'pages:page' l %}" />
          {% endif %}
          {% if lang_code != LANGUAGE_CODE  %}
            <link
                href="{% absolute_url request 'pages:page' l %}"
                hreflang="{{ lang_code }}"
                rel="alternate"
            />
          {% endif %}
        {% endif %}
      {% endwith %}{% endwith %}
    {% endfor %}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" integrity="sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'pages/codehilite.css' %}">
    {% if style %}
    <link rel="stylesheet" href="{% static style %}">
    {% else %}
    <link rel="stylesheet" href="{% static 'pages/main.css' %}">
    {% endif %}
    {% include 'pages/resources.html' with resources=resources.css %}
    {% block extra_css %}{% endblock %}
    {% include 'pages/math.html' %}
    {% include 'pages/resources.html' with resources=resources.js_head %}
    {% block extra_js_head %}{% endblock %}
  </head>

  <body>
    {% block text %}{% endblock %}
    {% block comments %}{% endblock %}
    {% block meta %}{% endblock %}


    {% if not o.nofooter or footerlink == o.name %}
    {% utf as u %}
    <footer>
      <br>

      {% if footerlink %}
        <a class="utf" href={% url 'pages:page' footerlink %}>{{ u }}</a><br>
      {% elif o.language == 'pt' %}
        <a class="utf" href={% url 'pages:page' 'index' %}>{{ u }}</a><br>
      {% else %}
        <a class="utf" href={% url 'pages:page' 'index_en' %}>{{ u }}</a><br>
      {% endif %}

    </footer>
    {% endif %}
    <br><br>

    {% block 'js' %}
    {% include 'pages/resources.html' with resources=resources.js_body %}
    <script src="{% static 'pages/script.js' %}"></script>
    {% endblock %}
    {% block extra_js_body %}{% endblock %}
  </body>
</html>

pages/templates/pages/comments.html
{% extends 'pages/base.html' %}
{% load  comments %}
{% load  rutf %}
{% load  i18n %}
{% load  page_tags %}

{% block comments %}

<h2>{{ o.title }}</h2>
<p class="subtitle">{% trans 'comments' %}</p>

{% get_comment_list for o.comment as comment_list %}
{% for comment in comment_list %}
  {% with forloop.counter0|to_classname as classname %}
    <div class="{{ classname }}">
    <p class="comment">{{ comment.comment }}</p>

    {% with comment.comment|truncatechars:100|slugify as id %}
    <p class="comment-data" id="{{ id }}">
    <a class="headerlink utf" href="#{{ id }}" title="permanent link">{% utf %}</a>
    {% endwith %}
    {% if comment.user_name %}
    {{ comment.user_name }} <b>|</b>
    {% endif %}
    {{comment.submit_date | date:"j.n.y <\b>|</\b> G:i" | safe }}
    </p>
    </div>
  {% endwith %}

{% endfor %}

{% if comment_list %}
<hr>
{% endif %}

<form action="{% if 'post' in request.path %}{{ request.path }}{% else %}{{ request.path }}/post{% endif %}" method="POST">
  {% csrf_token %}
  {% trans 'comments' as t %}
  {% with o.name|add:"/"|add:t as c %}
  <input type="hidden" name="next" value="{% url 'pages:page' c %}"/>
  {% endwith %}

  {% for field in form %}
    {% if field.is_hidden %}
      {{ field }}
    {% else %}
      {% if field.name != "url" %}
        {% if field.name == "name" or field.name == "comment" %}
        <div>
        {% endif %}
      <div class=form-{{ field.name }}
        {% if field.name == "honeypot" %} style="display:none;"{% endif %}>
        {% if field.errors %}
          <div class="error" id="error_{{ field.name }}">
            {{ field.errors.as_text|cut:"* "|cut:"."|lower }}
          </div>
        {% endif %}
        {{ field }}
      </div>
        {% if field.name == "email" or field.name == "comment" %}
        </div>
        {% endif %}
      {% endif %}

    {% endif %}
  {% endfor %}
  <div class="submit-container">
    <button class="submit" type="submit" name="post">
      <span class="utf">{% utf %}</span>
      {% comment %}Translators: comment verb{% endcomment %}
      {% trans 'comment' %}
    </button>
  </div>
</form>

{% endblock %}

pages/templates/pages/file_input.html
{% load i18n %}
<label class="file-label"  for="id_{{ widget.name }}">
  {% trans 'select file' %}
  <input type="{{ widget.type }}" name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}><span class="selected-file" aria-hidden="true">{% if filename %}({{ filename }}){% endif %}</span>
</label>

pages/templates/pages/form.html
{% load i18n rutf %}

<form action="{{ action }}"
      method="post"
      {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>
  {% csrf_token %}
  {% block 'formfields' %}
  {% for field in form %}
    <div>
      {{ field.label_tag|cut:":"|lower }}
      {% block 'errors' %}
      {% if field.errors %}
      <div>
        <span class="error" id="error_{{ field.name }}">
          {{ field.errors.as_text|cut:"* "|cut:"."|lower }}
        </span>
      </div>
      {% endif %}
      {% endblock %}
      <div{% if field.attrs %} {% include 'django/forms/attrs.html' with attrs=field.attrs %}{% endif %}>
        {{ field }}
      </div>
      {% if field.help_text %}
        <p class="help_text">{{ field.help_text }}</p>
      {% endif %}
    </div>
  {% endfor %}
  {% endblock %}

  {% block 'submit' %}
  <button type="submit">
    <span class="utf">{% utf %}</span>
    {% trans 'go' %}
    <span class="utf">{% utf %}</span>
  </button>
  {% endblock %}

  {% block 'result' %}
  {% if result %}<hr>{{ result }}{% endif %}
  {% endblock %}
</form>

pages/templates/pages/math.html
{% load static %}
{% if math %}
<script type="text/x-mathjax-config" src="{% static 'palco/mathjax-config.js' %}"></script>
<script defer src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script defer src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
{% endif %}

pages/templates/pages/menu.html
{% load i18n %}
{% load  i18n %}
{% load  rutf %}
{% load page_tags %}

<div class=small-right>
  <ul>

{% if o.hascomments and not iscomment %}
  {% comment %}Name of the page{% endcomment %}
  {% trans 'comments' as t %}
  {% with o.name|add:"/"|add:t as c %}
  <li><a class="stayblack" href={% url 'pages:page' c %}>
    <span class="utf">{% utf %}</span>
    &nbsp&nbsp
    {{ t }}
  </a>
  </li>
  {% endwith %}
{% endif %}

{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% for lang_code, lang_name in LANGUAGES %}
  {% if lang_code != LANGUAGE_CODE %}
    {% with lang_code|add:"_version" as att %} {# att = lang[0] + '_version'#}
    {% with o|getattrfilter:att as l %} {# l = getattr(o, att) #}
      {% if l %}
        {% get_language_info for lang_code as info %}

        <li><a class="stayblack" href={% url 'pages:page' l %}>
          <span class="utf">{% utf %}</span>
          &nbsp&nbsp
          {{ info.name_local|lower }}
        </a></li>

      {% endif %}
    {% endwith %}{% endwith %}
  {% endif %}
{% endfor %}

<li><a class="stayblack" href={% url 'pages:meta' o.name %}>
  <span class="utf">{% utf %}</span>
  &nbsp&nbsp
  {% trans 'meta' %}
</a></li>
  </ul>
</div>

pages/templates/pages/meta.html
{% extends 'pages/base.html' %}
{% load i18n %}
{% load comments %}

{% load rutf %}

{% block meta %}

<h2> {{ o.title }} </h2>
<br>

{% get_comment_count for o.comment as cc %}

<table style="width:100%">
  <tr>
    <td>
      <span class='utf'>{% utf %}</span>{% trans 'Publication date' %}:
    </td>
    <td style="text-align:right;">
        {{ o.pub_date|date:"j.n.y <\b>|</\b> G:i" |safe}}
    </td>
  </tr>
  <tr>
    <td>
      <span class='utf'>{% utf %}</span> {% trans 'Last modification' %}:
    </td>
    <td style="text-align:right;">
      {{ o.last_mod_date|date:"j.n.y <\b>|</\b> G:i" |safe }}
    <td>
  </tr>
  <tr>
    <td>
      <span class='utf'>{% utf %}</span> {% trans 'Comments' %}:
    </td>
    <td style="text-align:right;">
      {{ cc }}
    </td>
  </tr>
  <tr>
    <td>
      <span class='utf'>{% utf %}</span> {% trans 'Views' %}:
    </td>
    <td style="text-align:right;">
      {{ o.views }}
    </td>
  </tr>
</table>

<br><br>

{% with o.name|add:'.md' as md %}
{% trans 'here' as here %}
{% el 'https://gitlab.com/joaoseckler/website' here as ulgit %}
{% sl md here as pagelink %}

{% blocktrans%}This website's source code is
available {{ ulgit }}. A markdown version of this page is
available {{ pagelink }}{% endblocktrans %}
{% endwith %}

{% endblock %}

pages/templates/pages/page.html
{% extends 'pages/base.html' %}


{% block text %}
{{ text | safe }}

{% include 'pages/menu.html' %}
{% endblock %}

pages/templates/pages/resources.html
{% load static %}

{% for res in resources %}
{% if res.type_location == 'css' %}
<link
    rel="stylesheet"
    href="{% if res.is_static %}{% static res.resource %}{% else %}{{ res.resource }}{% endif %}"
    {% if res.attrs %}{{ res.attrs|safe }}{% endif %}
>
{% else %}
<script
    src="{% if res.is_static %}{% static res.resource %}{% else %}{{ res.resource }}{% endif %}"
    {% if res.attrs %}{{ res.attrs|safe }}{% endif %}
></script>
{% endif %}
{% endfor %}

pages/templates/pages/video.html
<video controls>
  {% for format in formats %}
  <source src="{{ url }}.{{ format }}">
  {% endfor %}
  {% if name %}
  <span>{{ name }}</span>
  {% endif %}
  {% for format in formats %}
  <a href="{{ url }}.{{ format }}">Download as {{ format }}</a>
  {% endfor %}
</video>